  let data = {
  featured: {
    0: 1
  },
  doors: {
    1: {
      id: 1,
      name: "alder",
      price: 1499.99,
      colors: ["clear", "provincial", "red chestnut"],
      description: "Won't open",
      rating: 4.5,
      numRatings: 6072,
      img: "clear-stain-alder.jpg",
      size: '48" x 96"',
    },
    2: {
      id: 2,
      name: "mahogany",
      price: 999.99,
      colors: ["clear", "red chestnut"],
      description: "Won't open",
      rating: 4.5,
      numRatings: 1023,
      img: "mahogany.jpg",
      size: '48" x 96"',
    },
    3: {
      id: 3,
      name: "steel",
      price: 1099.99,
      colors: ["clear", "white"],
      description: "Won't open",
      rating: 3.8,
      numRatings: 2341,
      img: "steel.jpg",
      size: '48" x 96"',
    },
    4: {
      id: 4,
      name: "mahogany2",
      price: 1299.99,
      colors: ["clear", "provincial", "red chestnut"],
      description: "Won't open",
      rating: 4.2,
      numRatings: 234,
      img: "mahogany2.jpg",
      size: '48" x 96"',
    },
    5: {
      id: 5,
      name: "steel2",
      price: 1249.99,
      colors: ["white"],
      description: "Won't open",
      rating: 4.4,
      numRatings: 6234,
      img: "steel2.jpg",
      size: '48" x 96"',
    },
    6: {
      id: 6,
      name: "fiberglass",
      price: 2599.99,
      colors: ["white", "provincial"],
      description: "Won't open",
      rating: 5,
      numRatings: 12,
      img: "fiberglass.jpg",
      size: '48" x 96"',
    },
    7: {
      id: 7,
      name: "fiberglass2",
      price: 2099.99,
      colors: ["clear", "provincial", "white"],
      description: "Won't open",
      rating: 3.8,
      numRatings: 234,
      img: "fiberglass2.jpg",
      size: '48" x 96"',
    },
  } 
};


module.exports = data;